# Generated by Django 5.2.6 on 2026-10-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_preset',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
